services:
  metabase:
    image: metabase/metabase:latest
    container_name: automations_metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    networks:
      - caddy_public
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${MB_POSTGRES_DB}
      MB_DB_PORT: 5432
      MB_DB_USER: ${MB_POSTGRES_USER}
      MB_DB_PASS: ${MB_POSTGRES_PASSWORD}
      MB_DB_HOST: postgres
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    container_name: automations_n8n
    hostname: n8n
    environment:
      N8N_HOST: localhost
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      WEBHOOK_URL: http://n8n:5678
      N8N_SECURE_COOKIE: false
      GENERIC_TIMEZONE: Europe/Paris
      NODE_ENV: production
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: ${N8N_POSTGRES_DB}
      DB_POSTGRESDB_USER: ${N8N_POSTGRES_USER}
      DB_POSTGRESDB_PASSWORD: ${N8N_POSTGRES_PASSWORD}
    ports:
      - 5678:5678
    links:
      - postgres
    networks:
      - automations
      - caddy_public
      - automations-internal
    volumes:
      - n8n_storage:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:latest
    container_name: automations_postgres
    hostname: postgres
    networks:
      - automations-internal
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - N8N_POSTGRES_USER
      - N8N_POSTGRES_PASSWORD
      - N8N_POSTGRES_DB
      - MB_POSTGRES_USER
      - MB_POSTGRES_PASSWORD
      - MB_POSTGRES_DB
    volumes:
      - db_storage:/var/lib/postgresql
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10


networks:
  automations:
    driver: bridge
    name: "automations"
  caddy_public:
    driver: bridge
    name: "caddy_public"
  automations-internal:
    driver: bridge

volumes:
  db_storage:
  n8n_storage:
